apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: example-app
data:
  default.conf: |
    server {
        listen 80;
        location / {
            return 200 'Hello from NGINX via ConfigMap!';
        }
    }